
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jpcojuiwvehqmucyaxvu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpwY29qdWl3dmVocW11Y3lheHZ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwMzg1NzQsImV4cCI6MjA1OTYxNDU3NH0.QaMhguF2hpmVuHJC0BQRGN0ZtnqoQihF4NbXiRqTiAM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
